# Generated by Django 3.1.7 on 2024-05-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
